### delete request
DELETE  http://localhost:3001/api/notes/1
Content-Type: application/json



### get request
GET http://localhost:3001/api/notes/
Content-Type: application/json

### send the post request
POST http://localhost:3001/api/notes/ 
Content-Type: application/json

{
    "content": "Yuvraj Singh",
    "important": "true"
}