### send the get request to the persons
POST  http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Yuvraj Singh",
    "number": "6280445789"
}

### send the get request
GET http://localhost:3001/api/persons
Content-Type: application/json

### send the delete request
DELETE http://localhost:3001/api/persons/6a420dcb1e0f9a7b4c57befa
Content-Type: application/json

### send the put request to the persons
PUT http://localhost:3001/api/persons/6a4210a41e0f9a7b4c57befc
Content-Type: application/json

{
    "name": "KD Pathak",
    "number": "789214563"
}